version: "3"

services:
  node:
    build: ./node
    networks:
      - nginx_network
    expose:
      - 3030

  nginx:
    build: ./nginx
    ports:
      - 443:443
    depends_on:
      - node
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
